/**
 * Stamp every photograph with a short hash of its own contents.
 *
 * This exists so images can be cached for a year. Their filenames never change,
 * unlike the hashed files under /assets/, so a long cache on a bare filename
 * would freeze a replaced photograph in visitors' browsers until the cache
 * expired. Adding ?v=<hash of the file> makes the URL change whenever the file
 * does, which is what makes "cache forever" safe rather than reckless.
 *
 * Runs as part of `npm run build`, in Node rather than Python, because it has to
 * work on the host's build machine as well as here. Same files in, same output,
 * so it only ever produces a diff when an image actually changed.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, sep } from 'node:path';

const ROOTS = ['public/images', 'public/fabrics'];
const OUT = 'src/data/imageVersions.ts';

function walk(dir, found = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, found);
    else found.push(full);
  }
  return found;
}

const versions = {};
for (const root of ROOTS) {
  for (const file of walk(root)) {
    // public/images/a/b.jpg -> /images/a/b.jpg, whatever separator the OS used
    const parts = file.split('/').flatMap((piece) => piece.split(sep));
    const url = '/' + parts.slice(1).join('/');
    versions[url] = createHash('sha256').update(readFileSync(file)).digest('hex').slice(0, 8);
  }
}

const keys = Object.keys(versions).sort();
const body = [
  '// Generated by scripts/fingerprint-images.mjs during the build. Do not edit.',
  '//',
  '// A short hash of each file, appended to its URL as ?v=... so that images can',
  '// be cached for a year and still update the moment one is replaced.',
  '',
  'export const IMAGE_VERSIONS: Record<string, string> = {',
  ...keys.map((k) => `  '${k}': '${versions[k]}',`),
  '};',
  '',
].join('\n');

let previous = '';
try {
  previous = readFileSync(OUT, 'utf8');
} catch {}
if (previous !== body) {
  writeFileSync(OUT, body);
  console.log(`fingerprinted ${keys.length} images -> ${OUT} (changed)`);
} else {
  console.log(`fingerprinted ${keys.length} images -> ${OUT} (no change)`);
}
