"""
Cut width variants of the large photographs and write a manifest for srcset.

The problem this solves: a category card is about 560 CSS pixels wide, and the
browser was downloading a 1792 pixel file to fill it. Resizing the original is
not the answer, because a retina screen genuinely wants those pixels. Offering
several widths is: the browser reads srcset, works out what the slot needs at
its own pixel density, and fetches only that one.

So nothing here reduces quality on any screen. Each display gets a file that
matches, rather than every display getting the largest.

Widths follow the slots in the layouts: 480 for fabric swatches on a phone, 768
for a swatch on a retina card, 1120 for a category card at 2x, 1600 for the
about gallery and full-bleed backgrounds.

Run:  python scripts/make-responsive-images.py [--write]
"""
import glob
import io
import os
import re
import sys

from PIL import Image

WRITE = '--write' in sys.argv
WIDTHS = (480, 768, 1120, 1600)
MIN_SOURCE = 900          # below this a single file is already small enough
QUALITY = 88
MANIFEST = 'src/data/imageVariants.ts'
SKIP = ('/images/logo-', '/images/contact/map.png', 'hero-figure.webp')


def referenced():
    out = set()
    for f in glob.glob('src/**/*.ts', recursive=True) + glob.glob('src/**/*.tsx', recursive=True):
        s = io.open(f, encoding='utf-8').read()
        for m in re.finditer(r"['\"](/(?:images|fabrics)/[^'\"]+)['\"]", s):
            out.add(m.group(1))
    return sorted(out)


def variant_path(path, width):
    stem, ext = os.path.splitext(path)
    return '%s-%dw%s' % (stem, width, ext)


manifest = {}
made = added = 0
print('%-58s %-10s %s' % ('file', 'source', 'variants written'))
for path in referenced():
    if any(s in path for s in SKIP) or not os.path.exists('public' + path):
        continue
    im = Image.open('public' + path)
    if im.width < MIN_SOURCE:
        continue
    im = im.convert('RGB')

    widths = []
    for w in WIDTHS:
        if w >= im.width * 0.92:      # no point in a variant the size of the source
            continue
        out = 'public' + variant_path(path, w)
        widths.append(w)
        if not WRITE:
            continue
        if os.path.exists(out):
            continue
        small = im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)
        small.save(out, 'JPEG', quality=QUALITY, optimize=True, progressive=True)
        made += 1
        added += os.path.getsize(out)

    if widths:
        manifest[path] = widths + [im.width]
        print('%-58s %5dpx     %s' % (path[-58:], im.width, ', '.join('%dw' % w for w in widths)))

if WRITE:
    lines = [
        '// Generated by scripts/make-responsive-images.py. Do not edit by hand.',
        '//',
        '// Maps each photograph to the widths that exist on disk, so PlaceholderImage',
        '// can build a srcset and let the browser pick one that matches the slot it is',
        '// filling. The last number in each list is the original width.',
        '',
        'export const IMAGE_VARIANTS: Record<string, number[]> = {',
    ]
    for path in sorted(manifest):
        lines.append("  '%s': [%s]," % (path, ', '.join(str(w) for w in manifest[path])))
    lines += ['};', '']
    io.open(MANIFEST, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))
    print('\nwrote %s with %d entries' % (MANIFEST, len(manifest)))
    print('%d variant files, %.1f MB added' % (made, added / 1e6))
else:
    print('\n%d photographs would get variants. dry run, nothing written.' % len(manifest))
