// Generated by scripts/make-responsive-images.py. Do not edit by hand.
//
// Maps each photograph to the widths that exist on disk, so PlaceholderImage
// can build a srcset and let the browser pick one that matches the slot it is
// filling. The last number in each list is the original width.

export const IMAGE_VARIANTS: Record<string, number[]> = {
  '/fabrics/ankara-1.jpg': [480, 768, 1120, 1600, 2400],
  '/fabrics/tissin-1.jpg': [480, 768, 1162],
  '/images/about/behind_the_scene/stitching-tissin.jpg': [480, 768, 1120, 1600],
  '/images/about/behind_the_scene/tissin-materials.jpg': [480, 768, 1120, 1600],
  '/images/contact/contact-bg.jpg': [480, 768, 1120, 1600, 2400],
  '/images/craftsmanship/blue-dress.jpg': [480, 768, 975],
  '/images/craftsmanship/mama-afrika.jpg': [480, 768, 1200],
  '/images/home/five_categories/corporate-uniforms.jpg': [480, 768, 1120],
  '/images/home/five_categories/school-uniforms.jpg': [480, 768, 1120, 1600, 1792],
  '/images/home/our-story.jpg': [480, 768, 1120, 1240],
  '/images/products/bespoke-tailoring/evening-dresses.jpg': [480, 768, 960],
  '/images/products/corporate-uniforms/hotel-staff.jpg': [480, 768, 900],
  '/images/products/corporate-uniforms/logo-embroidery.jpg': [480, 768, 1200],
  '/images/products/corporate-uniforms/restaurant-staff.jpeg': [480, 768, 1080],
  '/images/products/mushanana-collection/bridesmaids.jpg': [480, 768, 960],
  '/images/products/mushanana-collection/dancing-troupes.jpeg': [480, 768, 1080],
  '/images/products/mushanana-collection/male-umushanana.jpg': [480, 768, 1199],
  '/images/services/alterations-repairs/damaged-cloth-repair.jpg': [480, 768, 1024],
  '/images/services/alterations-repairs/shirt-altered.jpg': [480, 768, 960],
  '/images/services/fabric-development/picking-fabric.jpg': [480, 768, 1000],
  '/images/services/fashion-consultation/colour-analysis.jpg': [480, 768, 960],
  '/images/services/fashion-consultation/designer-fitting.jpg': [480, 768, 960],
};
